Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.define "maquina1" do |m1|
    m1.vm.box = "ubuntu/trusty64"
    m1.vm.network "public_network", type: "dhcp"
    m1.vm.provision "file",source:"resolv.conf",destination:"/tmp/resolv.conf"
    m1.vm.provision "shell", path: "script.sh"
  end
  config.vm.define "maquina2" do |m2|
    m2.vm.box = "ubuntu/trusty64"
    m2.vm.network "private_network", ip: "172.16.10.10"
    m2.vm.provision "file",source:"resolv.conf",destination:"/tmp/resolv.conf"
    m2.vm.provision "shell", path: "script.sh"
  end
  config.vm.define "maquina3" do |m3|
    m3.vm.box = "ubuntu/trusty64"
    m3.vm.network "private_network", ip: "172.16.10.20"
    m3.vm.provision "file",source:"resolv.conf",destination:"/tmp/resolv.conf"
    m3.vm.provision "shell", path: "script.sh"
  end
  config.vm.define "maquina4" do |m4|
    m4.vm.box = "ubuntu/trusty64"
    m4.vm.network "private_network", ip: "172.16.10.30"
    m4.vm.provision "file",source:"resolv.conf",destination:"/tmp/resolv.conf"
    m4.vm.provision "shell", path: "script.sh"
  end
 
end
