---
- hosts: all
  become: true
  roles:
     - role: geerlingguy.mysql
       mysql_user_home: /root
       mysql_user_name: root
       mysql_user_password: root
       mysql_databases:
         - name: alberto
       mysql_users:
         - name: alberto
           password: 2asirtriana
           priv: "*.*:ALL"
  tasks:
     - name: updatecache
       action: apt update_cache=true
